// ===================== MOCK DATA =====================
// In-memory mock data for all models, used when PostgreSQL is unavailable.
// All IDs use simple sequential patterns (e.g., "user-1", "contact-1").

// ===================== TYPE DEFINITIONS =====================
export interface MockUser {
  id: string;
  name: string;
  email: string;
  emailVerified: string | null;
  hashedPassword: string;
  image: string | null;
  role: "ADMIN" | "MANAGER" | "MEMBER";
  createdAt: string;
  updatedAt: string;
}

export interface MockCompany {
  id: string;
  name: string;
  domain: string | null;
  industry: string | null;
  phone: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  description: string | null;
  annualRevenue: number | null;
  employeeCount: number | null;
  ownerId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface MockContact {
  id: string;
  email: string | null;
  firstName: string;
  lastName: string;
  phone: string | null;
  jobTitle: string | null;
  avatar: string | null;
  lifecycleStage: string;
  leadStatus: string | null;
  source: string | null;
  ownerId: string | null;
  companyId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface MockDeal {
  id: string;
  name: string;
  amount: number | null;
  currency: string;
  closeDate: string | null;
  probability: number | null;
  stageId: string;
  pipelineId: string;
  ownerId: string | null;
  companyId: string | null;
  priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
  createdAt: string;
  updatedAt: string;
}

export interface MockTicket {
  id: string;
  subject: string;
  description: string | null;
  status: "OPEN" | "IN_PROGRESS" | "WAITING" | "CLOSED";
  priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
  category: string | null;
  ownerId: string | null;
  contactId: string | null;
  companyId: string | null;
  pipelineId: string | null;
  stageId: string | null;
  slaDeadline: string | null;
  closedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface MockTask {
  id: string;
  title: string;
  description: string | null;
  dueDate: string | null;
  priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
  status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "DEFERRED";
  type: "TODO" | "CALL" | "EMAIL" | "MEETING" | "FOLLOW_UP";
  ownerId: string | null;
  contactId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface MockActivity {
  id: string;
  type: string;
  subject: string | null;
  body: string | null;
  metadata: Record<string, unknown> | null;
  userId: string | null;
  contactId: string | null;
  companyId: string | null;
  dealId: string | null;
  ticketId: string | null;
  createdAt: string;
}

export interface MockNote {
  id: string;
  body: string;
  userId: string | null;
  contactId: string | null;
  companyId: string | null;
  dealId: string | null;
  ticketId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface MockPipelineStage {
  id: string;
  name: string;
  probability: number;
  order: number;
  color: string;
  pipelineId: string;
}

export interface MockPipeline {
  id: string;
  name: string;
  isDefault: boolean;
  order: number;
  createdAt: string;
  updatedAt: string;
}

export interface MockWorkflow {
  id: string;
  name: string;
  type: string;
  active: boolean;
  lastModified: string;
  enrolledCount: number;
  trigger: string;
  actions: string[];
  createdAt: string;
}

export interface MockSequence {
  id: string;
  name: string;
  steps: { type: string; label: string; delay: number }[];
  stepsCount: number;
  enrolled: number;
  replyRate: number;
  meetingRate: number;
  active: boolean;
  createdAt: string;
  ownerId: string | null;
  ownerName: string | null;
}

// ===================== USERS =====================
export const mockUsers: MockUser[] = [
  {
    id: "user-1",
    name: "佐藤 匠",
    email: "sato@example.com",
    emailVerified: null,
    hashedPassword: "$2a$12$dummy_hash_for_mock_data_1",
    image: null,
    role: "ADMIN" as const,
    createdAt: "2025-04-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "user-2",
    name: "田中 美咲",
    email: "tanaka@example.com",
    emailVerified: null,
    hashedPassword: "$2a$12$dummy_hash_for_mock_data_2",
    image: null,
    role: "MANAGER" as const,
    createdAt: "2025-04-05T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "user-3",
    name: "鈴木 大輔",
    email: "suzuki@example.com",
    emailVerified: null,
    hashedPassword: "$2a$12$dummy_hash_for_mock_data_3",
    image: null,
    role: "MEMBER" as const,
    createdAt: "2025-05-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "user-4",
    name: "山田 花子",
    email: "yamada@example.com",
    emailVerified: null,
    hashedPassword: "$2a$12$dummy_hash_for_mock_data_4",
    image: null,
    role: "MEMBER" as const,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "user-5",
    name: "伊藤 健太",
    email: "ito@example.com",
    emailVerified: null,
    hashedPassword: "$2a$12$dummy_hash_for_mock_data_5",
    image: null,
    role: "MEMBER" as const,
    createdAt: "2025-07-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
];

// ===================== COMPANIES =====================
export const mockCompanies: MockCompany[] = [
  {
    id: "company-1",
    name: "株式会社テクノロジー",
    domain: "tech-corp.co.jp",
    industry: "IT・ソフトウェア",
    phone: "03-1234-5678",
    city: "東京都",
    state: "渋谷区",
    country: "日本",
    description: "最先端のクラウドソリューションを提供するIT企業",
    annualRevenue: 5000000000,
    employeeCount: 350,
    ownerId: "user-1",
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "company-2",
    name: "サクラソフトウェア株式会社",
    domain: "sakura-soft.jp",
    industry: "IT・ソフトウェア",
    phone: "03-2345-6789",
    city: "東京都",
    state: "港区",
    country: "日本",
    description: "業務効率化SaaSを開発するスタートアップ",
    annualRevenue: 800000000,
    employeeCount: 85,
    ownerId: "user-2",
    createdAt: "2025-07-15T00:00:00Z",
    updatedAt: "2026-02-20T00:00:00Z",
  },
  {
    id: "company-3",
    name: "富士マーケティング株式会社",
    domain: "fuji-marketing.co.jp",
    industry: "広告・マーケティング",
    phone: "06-3456-7890",
    city: "大阪府",
    state: "中央区",
    country: "日本",
    description: "デジタルマーケティング支援を行う総合代理店",
    annualRevenue: 3000000000,
    employeeCount: 200,
    ownerId: "user-1",
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "company-4",
    name: "グローバルコンサルティング株式会社",
    domain: "global-consulting.co.jp",
    industry: "コンサルティング",
    phone: "03-4567-8901",
    city: "東京都",
    state: "千代田区",
    country: "日本",
    description: "DX推進を支援する経営コンサルティングファーム",
    annualRevenue: 12000000000,
    employeeCount: 600,
    ownerId: "user-3",
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "company-5",
    name: "大和建設株式会社",
    domain: "yamato-kensetsu.co.jp",
    industry: "建設・不動産",
    phone: "052-5678-9012",
    city: "名古屋市",
    state: "中区",
    country: "日本",
    description: "商業施設・オフィスビルの設計施工を手がける建設会社",
    annualRevenue: 25000000000,
    employeeCount: 1200,
    ownerId: "user-4",
    createdAt: "2025-09-15T00:00:00Z",
    updatedAt: "2026-02-28T00:00:00Z",
  },
  {
    id: "company-6",
    name: "ネクストイノベーション株式会社",
    domain: "next-innovation.jp",
    industry: "IT・ソフトウェア",
    phone: "03-6789-0123",
    city: "東京都",
    state: "新宿区",
    country: "日本",
    description: "AIとIoTを活用した製造業DXソリューション",
    annualRevenue: 1500000000,
    employeeCount: 120,
    ownerId: "user-2",
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "company-7",
    name: "みずほフィナンシャルサービス株式会社",
    domain: "mizuho-fs.co.jp",
    industry: "金融・保険",
    phone: "03-7890-1234",
    city: "東京都",
    state: "中央区",
    country: "日本",
    description: "法人向け金融サービスを提供するフィナンシャル企業",
    annualRevenue: 50000000000,
    employeeCount: 3000,
    ownerId: "user-1",
    createdAt: "2025-10-15T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
  },
  {
    id: "company-8",
    name: "北海道食品株式会社",
    domain: "hokkaido-foods.co.jp",
    industry: "食品・飲料",
    phone: "011-8901-2345",
    city: "札幌市",
    state: "北区",
    country: "日本",
    description: "北海道産の食材を活かした食品メーカー",
    annualRevenue: 8000000000,
    employeeCount: 500,
    ownerId: "user-5",
    createdAt: "2025-11-01T00:00:00Z",
    updatedAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "company-9",
    name: "エコエナジー株式会社",
    domain: "eco-energy.co.jp",
    industry: "エネルギー・環境",
    phone: "03-9012-3456",
    city: "東京都",
    state: "品川区",
    country: "日本",
    description: "再生可能エネルギー事業を展開するクリーンテック企業",
    annualRevenue: 6000000000,
    employeeCount: 250,
    ownerId: "user-3",
    createdAt: "2025-11-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "company-10",
    name: "メディカルケア株式会社",
    domain: "medical-care.co.jp",
    industry: "医療・ヘルスケア",
    phone: "06-0123-4567",
    city: "大阪府",
    state: "北区",
    country: "日本",
    description: "医療機関向けITソリューションを提供するヘルステック企業",
    annualRevenue: 2000000000,
    employeeCount: 150,
    ownerId: "user-4",
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "company-11",
    name: "スマートロジスティクス株式会社",
    domain: "smart-logistics.jp",
    industry: "物流・運送",
    phone: "045-1234-5678",
    city: "横浜市",
    state: "西区",
    country: "日本",
    description: "AIを活用した次世代物流プラットフォーム",
    annualRevenue: 10000000000,
    employeeCount: 800,
    ownerId: "user-5",
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2026-02-25T00:00:00Z",
  },
  {
    id: "company-12",
    name: "クリエイティブデザイン株式会社",
    domain: "creative-design.jp",
    industry: "デザイン・クリエイティブ",
    phone: "03-2345-6780",
    city: "東京都",
    state: "目黒区",
    country: "日本",
    description: "UI/UXデザインとブランディングを専門とするデザインスタジオ",
    annualRevenue: 500000000,
    employeeCount: 45,
    ownerId: "user-2",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
];

// ===================== CONTACTS =====================
export const mockContacts: MockContact[] = [
  {
    id: "contact-1",
    email: "yamamoto.taro@tech-corp.co.jp",
    firstName: "太郎",
    lastName: "山本",
    phone: "090-1234-5678",
    jobTitle: "取締役CTO",
    avatar: null,
    lifecycleStage: "CUSTOMER" as const,
    leadStatus: "OPEN_DEAL" as const,
    source: "ウェブサイト",
    ownerId: "user-1",
    companyId: "company-1",
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "contact-2",
    email: "suzuki.hanako@sakura-soft.jp",
    firstName: "花子",
    lastName: "鈴木",
    phone: "090-2345-6789",
    jobTitle: "マーケティング部長",
    avatar: null,
    lifecycleStage: "OPPORTUNITY" as const,
    leadStatus: "CONNECTED" as const,
    source: "展示会",
    ownerId: "user-2",
    companyId: "company-2",
    createdAt: "2025-08-15T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "contact-3",
    email: "tanaka.kenji@fuji-marketing.co.jp",
    firstName: "健二",
    lastName: "田中",
    phone: "080-3456-7890",
    jobTitle: "代表取締役",
    avatar: null,
    lifecycleStage: "SQL" as const,
    leadStatus: "IN_PROGRESS" as const,
    source: "紹介",
    ownerId: "user-1",
    companyId: "company-3",
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "contact-4",
    email: "watanabe.yuki@global-consulting.co.jp",
    firstName: "雄希",
    lastName: "渡辺",
    phone: "090-4567-8901",
    jobTitle: "シニアコンサルタント",
    avatar: null,
    lifecycleStage: "MQL" as const,
    leadStatus: "OPEN" as const,
    source: "ウェビナー",
    ownerId: "user-3",
    companyId: "company-4",
    createdAt: "2025-09-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "contact-5",
    email: "nakamura.akiko@yamato-kensetsu.co.jp",
    firstName: "明子",
    lastName: "中村",
    phone: "080-5678-9012",
    jobTitle: "総務部長",
    avatar: null,
    lifecycleStage: "LEAD" as const,
    leadStatus: "NEW" as const,
    source: "ウェブサイト",
    ownerId: "user-4",
    companyId: "company-5",
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-02-28T00:00:00Z",
  },
  {
    id: "contact-6",
    email: "kobayashi.daisuke@next-innovation.jp",
    firstName: "大輔",
    lastName: "小林",
    phone: "090-6789-0123",
    jobTitle: "プロダクトマネージャー",
    avatar: null,
    lifecycleStage: "OPPORTUNITY" as const,
    leadStatus: "CONNECTED" as const,
    source: "セミナー",
    ownerId: "user-2",
    companyId: "company-6",
    createdAt: "2025-10-15T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "contact-7",
    email: "saito.megumi@mizuho-fs.co.jp",
    firstName: "めぐみ",
    lastName: "斎藤",
    phone: "080-7890-1234",
    jobTitle: "IT企画部マネージャー",
    avatar: null,
    lifecycleStage: "SQL" as const,
    leadStatus: "IN_PROGRESS" as const,
    source: "紹介",
    ownerId: "user-1",
    companyId: "company-7",
    createdAt: "2025-11-01T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
  },
  {
    id: "contact-8",
    email: "takahashi.ryo@hokkaido-foods.co.jp",
    firstName: "亮",
    lastName: "高橋",
    phone: "090-8901-2345",
    jobTitle: "情報システム部長",
    avatar: null,
    lifecycleStage: "CUSTOMER" as const,
    leadStatus: "OPEN_DEAL" as const,
    source: "展示会",
    ownerId: "user-5",
    companyId: "company-8",
    createdAt: "2025-11-15T00:00:00Z",
    updatedAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "contact-9",
    email: "ito.sakura@eco-energy.co.jp",
    firstName: "さくら",
    lastName: "伊藤",
    phone: "080-9012-3456",
    jobTitle: "事業開発マネージャー",
    avatar: null,
    lifecycleStage: "MQL" as const,
    leadStatus: "ATTEMPTED_TO_CONTACT" as const,
    source: "ウェブサイト",
    ownerId: "user-3",
    companyId: "company-9",
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "contact-10",
    email: "matsumoto.hiroshi@medical-care.co.jp",
    firstName: "浩",
    lastName: "松本",
    phone: "090-0123-4567",
    jobTitle: "営業部長",
    avatar: null,
    lifecycleStage: "LEAD" as const,
    leadStatus: "NEW" as const,
    source: "広告",
    ownerId: "user-4",
    companyId: "company-10",
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "contact-11",
    email: "inoue.tomoko@smart-logistics.jp",
    firstName: "智子",
    lastName: "井上",
    phone: "080-1111-2222",
    jobTitle: "物流企画リーダー",
    avatar: null,
    lifecycleStage: "SUBSCRIBER" as const,
    leadStatus: null,
    source: "ウェブサイト",
    ownerId: "user-5",
    companyId: "company-11",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-02-25T00:00:00Z",
  },
  {
    id: "contact-12",
    email: "kimura.shota@creative-design.jp",
    firstName: "翔太",
    lastName: "木村",
    phone: "090-3333-4444",
    jobTitle: "クリエイティブディレクター",
    avatar: null,
    lifecycleStage: "OPPORTUNITY" as const,
    leadStatus: "CONNECTED" as const,
    source: "紹介",
    ownerId: "user-2",
    companyId: "company-12",
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "contact-13",
    email: "yoshida.mai@tech-corp.co.jp",
    firstName: "麻衣",
    lastName: "吉田",
    phone: "080-5555-6666",
    jobTitle: "エンジニアリングマネージャー",
    avatar: null,
    lifecycleStage: "CUSTOMER" as const,
    leadStatus: "OPEN_DEAL" as const,
    source: "ウェブサイト",
    ownerId: "user-1",
    companyId: "company-1",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "contact-14",
    email: "hayashi.takeshi@fuji-marketing.co.jp",
    firstName: "武",
    lastName: "林",
    phone: "090-7777-8888",
    jobTitle: "デジタル戦略部マネージャー",
    avatar: null,
    lifecycleStage: "SQL" as const,
    leadStatus: "IN_PROGRESS" as const,
    source: "セミナー",
    ownerId: "user-3",
    companyId: "company-3",
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "contact-15",
    email: "morita.yui@global-consulting.co.jp",
    firstName: "結衣",
    lastName: "森田",
    phone: "080-9999-0000",
    jobTitle: "マネージングディレクター",
    avatar: null,
    lifecycleStage: "EVANGELIST" as const,
    leadStatus: null,
    source: "紹介",
    ownerId: "user-1",
    companyId: "company-4",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "contact-16",
    email: "ono.kaito@next-innovation.jp",
    firstName: "海斗",
    lastName: "小野",
    phone: "090-1122-3344",
    jobTitle: "AIエンジニア",
    avatar: null,
    lifecycleStage: "LEAD" as const,
    leadStatus: "OPEN" as const,
    source: "ウェビナー",
    ownerId: "user-4",
    companyId: "company-6",
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "contact-17",
    email: "shimizu.aoi@mizuho-fs.co.jp",
    firstName: "葵",
    lastName: "清水",
    phone: "080-5566-7788",
    jobTitle: "リスク管理部マネージャー",
    avatar: null,
    lifecycleStage: "MQL" as const,
    leadStatus: "ATTEMPTED_TO_CONTACT" as const,
    source: "ウェブサイト",
    ownerId: "user-5",
    companyId: "company-7",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
  },
  {
    id: "contact-18",
    email: "fujita.ren@yamato-kensetsu.co.jp",
    firstName: "蓮",
    lastName: "藤田",
    phone: "090-9900-1122",
    jobTitle: "設計部主任",
    avatar: null,
    lifecycleStage: "SUBSCRIBER" as const,
    leadStatus: null,
    source: "広告",
    ownerId: "user-3",
    companyId: "company-5",
    createdAt: "2026-02-20T00:00:00Z",
    updatedAt: "2026-02-28T00:00:00Z",
  },
  {
    id: "contact-19",
    email: "ogawa.mana@eco-energy.co.jp",
    firstName: "愛",
    lastName: "小川",
    phone: "080-3344-5566",
    jobTitle: "サステナビリティ推進室長",
    avatar: null,
    lifecycleStage: "SQL" as const,
    leadStatus: "IN_PROGRESS" as const,
    source: "展示会",
    ownerId: "user-2",
    companyId: "company-9",
    createdAt: "2026-02-25T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "contact-20",
    email: "hasegawa.sho@hokkaido-foods.co.jp",
    firstName: "翔",
    lastName: "長谷川",
    phone: "090-7788-9900",
    jobTitle: "経営企画部次長",
    avatar: null,
    lifecycleStage: "OTHER" as const,
    leadStatus: "BAD_TIMING" as const,
    source: "紹介",
    ownerId: "user-1",
    companyId: "company-8",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
];

// ===================== PIPELINE & STAGES =====================
export const mockPipelineStages: MockPipelineStage[] = [
  { id: "stage-1", name: "初回商談", probability: 20, order: 0, color: "#3B82F6", pipelineId: "pipeline-1" },
  { id: "stage-2", name: "提案中", probability: 40, order: 1, color: "#8B5CF6", pipelineId: "pipeline-1" },
  { id: "stage-3", name: "見積提出", probability: 60, order: 2, color: "#F59E0B", pipelineId: "pipeline-1" },
  { id: "stage-4", name: "交渉中", probability: 80, order: 3, color: "#F97316", pipelineId: "pipeline-1" },
  { id: "stage-5", name: "契約締結", probability: 100, order: 4, color: "#10B981", pipelineId: "pipeline-1" },
  { id: "stage-6", name: "失注", probability: 0, order: 5, color: "#EF4444", pipelineId: "pipeline-1" },
];

export const mockPipelines: MockPipeline[] = [
  {
    id: "pipeline-1",
    name: "デフォルトパイプライン",
    isDefault: true,
    order: 0,
    createdAt: "2025-04-01T00:00:00Z",
    updatedAt: "2025-04-01T00:00:00Z",
  },
];

// ===================== DEALS =====================
export const mockDeals: MockDeal[] = [
  {
    id: "deal-1",
    name: "クラウド基盤構築プロジェクト",
    amount: 15000000,
    currency: "JPY",
    closeDate: "2026-04-30T00:00:00Z",
    probability: 80,
    stageId: "stage-4",
    pipelineId: "pipeline-1",
    ownerId: "user-1",
    companyId: "company-1",
    priority: "HIGH" as const,
    createdAt: "2025-11-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "deal-2",
    name: "マーケティングオートメーション導入",
    amount: 8000000,
    currency: "JPY",
    closeDate: "2026-05-15T00:00:00Z",
    probability: 60,
    stageId: "stage-3",
    pipelineId: "pipeline-1",
    ownerId: "user-2",
    companyId: "company-2",
    priority: "MEDIUM" as const,
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "deal-3",
    name: "デジタル広告一括運用契約",
    amount: 25000000,
    currency: "JPY",
    closeDate: "2026-03-31T00:00:00Z",
    probability: 40,
    stageId: "stage-2",
    pipelineId: "pipeline-1",
    ownerId: "user-1",
    companyId: "company-3",
    priority: "HIGH" as const,
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "deal-4",
    name: "DX推進コンサルティング",
    amount: 50000000,
    currency: "JPY",
    closeDate: "2026-06-30T00:00:00Z",
    probability: 20,
    stageId: "stage-1",
    pipelineId: "pipeline-1",
    ownerId: "user-3",
    companyId: "company-4",
    priority: "URGENT" as const,
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "deal-5",
    name: "施工管理システム導入",
    amount: 12000000,
    currency: "JPY",
    closeDate: "2026-05-31T00:00:00Z",
    probability: 20,
    stageId: "stage-1",
    pipelineId: "pipeline-1",
    ownerId: "user-4",
    companyId: "company-5",
    priority: "MEDIUM" as const,
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-02-28T00:00:00Z",
  },
  {
    id: "deal-6",
    name: "AI予測分析ツール",
    amount: 6000000,
    currency: "JPY",
    closeDate: "2026-04-15T00:00:00Z",
    probability: 60,
    stageId: "stage-3",
    pipelineId: "pipeline-1",
    ownerId: "user-2",
    companyId: "company-6",
    priority: "HIGH" as const,
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "deal-7",
    name: "金融システムモダナイゼーション",
    amount: 35000000,
    currency: "JPY",
    closeDate: "2026-09-30T00:00:00Z",
    probability: 40,
    stageId: "stage-2",
    pipelineId: "pipeline-1",
    ownerId: "user-1",
    companyId: "company-7",
    priority: "URGENT" as const,
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
  },
  {
    id: "deal-8",
    name: "食品トレーサビリティシステム",
    amount: 4500000,
    currency: "JPY",
    closeDate: "2026-04-30T00:00:00Z",
    probability: 100,
    stageId: "stage-5",
    pipelineId: "pipeline-1",
    ownerId: "user-5",
    companyId: "company-8",
    priority: "LOW" as const,
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "deal-9",
    name: "再エネモニタリングダッシュボード",
    amount: 7500000,
    currency: "JPY",
    closeDate: "2026-05-15T00:00:00Z",
    probability: 80,
    stageId: "stage-4",
    pipelineId: "pipeline-1",
    ownerId: "user-3",
    companyId: "company-9",
    priority: "MEDIUM" as const,
    createdAt: "2026-01-25T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "deal-10",
    name: "電子カルテ連携システム",
    amount: 18000000,
    currency: "JPY",
    closeDate: "2026-07-31T00:00:00Z",
    probability: 40,
    stageId: "stage-2",
    pipelineId: "pipeline-1",
    ownerId: "user-4",
    companyId: "company-10",
    priority: "HIGH" as const,
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "deal-11",
    name: "物流最適化AIプラットフォーム",
    amount: 22000000,
    currency: "JPY",
    closeDate: "2026-08-31T00:00:00Z",
    probability: 20,
    stageId: "stage-1",
    pipelineId: "pipeline-1",
    ownerId: "user-5",
    companyId: "company-11",
    priority: "MEDIUM" as const,
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-02-25T00:00:00Z",
  },
  {
    id: "deal-12",
    name: "ブランドリニューアルプロジェクト",
    amount: 3000000,
    currency: "JPY",
    closeDate: "2026-04-15T00:00:00Z",
    probability: 60,
    stageId: "stage-3",
    pipelineId: "pipeline-1",
    ownerId: "user-2",
    companyId: "company-12",
    priority: "LOW" as const,
    createdAt: "2026-02-20T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "deal-13",
    name: "全社CRM統合プロジェクト",
    amount: 45000000,
    currency: "JPY",
    closeDate: "2026-03-15T00:00:00Z",
    probability: 100,
    stageId: "stage-5",
    pipelineId: "pipeline-1",
    ownerId: "user-1",
    companyId: "company-4",
    priority: "URGENT" as const,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "deal-14",
    name: "ウェブサイトリプレイス",
    amount: 500000,
    currency: "JPY",
    closeDate: "2026-02-28T00:00:00Z",
    probability: 0,
    stageId: "stage-6",
    pipelineId: "pipeline-1",
    ownerId: "user-3",
    companyId: "company-12",
    priority: "LOW" as const,
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2026-02-28T00:00:00Z",
  },
  {
    id: "deal-15",
    name: "セキュリティ監査サービス",
    amount: 9000000,
    currency: "JPY",
    closeDate: "2026-06-15T00:00:00Z",
    probability: 80,
    stageId: "stage-4",
    pipelineId: "pipeline-1",
    ownerId: "user-1",
    companyId: "company-7",
    priority: "HIGH" as const,
    createdAt: "2026-02-25T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
  },
];

// DealContact join table references
export const mockDealContacts = [
  { dealId: "deal-1", contactId: "contact-1" },
  { dealId: "deal-1", contactId: "contact-13" },
  { dealId: "deal-2", contactId: "contact-2" },
  { dealId: "deal-3", contactId: "contact-3" },
  { dealId: "deal-3", contactId: "contact-14" },
  { dealId: "deal-4", contactId: "contact-4" },
  { dealId: "deal-4", contactId: "contact-15" },
  { dealId: "deal-5", contactId: "contact-5" },
  { dealId: "deal-6", contactId: "contact-6" },
  { dealId: "deal-7", contactId: "contact-7" },
  { dealId: "deal-7", contactId: "contact-17" },
  { dealId: "deal-8", contactId: "contact-8" },
  { dealId: "deal-9", contactId: "contact-9" },
  { dealId: "deal-9", contactId: "contact-19" },
  { dealId: "deal-10", contactId: "contact-10" },
  { dealId: "deal-11", contactId: "contact-11" },
  { dealId: "deal-12", contactId: "contact-12" },
  { dealId: "deal-13", contactId: "contact-15" },
  { dealId: "deal-14", contactId: "contact-12" },
  { dealId: "deal-15", contactId: "contact-7" },
];

// ===================== TICKETS =====================
export const mockTickets: MockTicket[] = [
  {
    id: "ticket-1",
    subject: "ログイン認証エラーが頻発",
    description: "ユーザーから、ログイン時に認証エラーが頻発するとの報告があります。特にモバイルブラウザで発生率が高い状況です。",
    status: "IN_PROGRESS" as const,
    priority: "HIGH" as const,
    category: "バグ",
    ownerId: "user-3",
    contactId: "contact-1",
    companyId: "company-1",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-15T18:00:00Z",
    closedAt: null,
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-03-13T14:00:00Z",
  },
  {
    id: "ticket-2",
    subject: "レポート出力のCSVフォーマット修正依頼",
    description: "CSVエクスポート時に、日本語文字化けが発生します。エンコーディングをShift-JISに変更してほしい。",
    status: "OPEN" as const,
    priority: "MEDIUM" as const,
    category: "機能改善",
    ownerId: "user-4",
    contactId: "contact-2",
    companyId: "company-2",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-20T18:00:00Z",
    closedAt: null,
    createdAt: "2026-03-11T10:30:00Z",
    updatedAt: "2026-03-11T10:30:00Z",
  },
  {
    id: "ticket-3",
    subject: "API連携のレスポンス遅延",
    description: "外部API連携時のレスポンスが5秒以上かかることがあり、ユーザー体験に影響しています。",
    status: "IN_PROGRESS" as const,
    priority: "URGENT" as const,
    category: "パフォーマンス",
    ownerId: "user-1",
    contactId: "contact-7",
    companyId: "company-7",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-14T18:00:00Z",
    closedAt: null,
    createdAt: "2026-03-08T15:00:00Z",
    updatedAt: "2026-03-13T11:00:00Z",
  },
  {
    id: "ticket-4",
    subject: "ダッシュボードのグラフ表示不具合",
    description: "売上推移グラフで、3月分のデータが正しく表示されません。",
    status: "OPEN" as const,
    priority: "MEDIUM" as const,
    category: "バグ",
    ownerId: "user-5",
    contactId: "contact-8",
    companyId: "company-8",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-18T18:00:00Z",
    closedAt: null,
    createdAt: "2026-03-12T08:00:00Z",
    updatedAt: "2026-03-12T08:00:00Z",
  },
  {
    id: "ticket-5",
    subject: "新機能：Slackインテグレーション要望",
    description: "通知機能にSlack連携を追加してほしいという要望です。特に、取引ステージ変更時の自動通知が求められています。",
    status: "WAITING" as const,
    priority: "LOW" as const,
    category: "機能要望",
    ownerId: "user-2",
    contactId: "contact-6",
    companyId: "company-6",
    pipelineId: null,
    stageId: null,
    slaDeadline: null,
    closedAt: null,
    createdAt: "2026-03-05T14:00:00Z",
    updatedAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "ticket-6",
    subject: "メールテンプレートの変数展開不具合",
    description: "メールテンプレート内の{{company_name}}変数が正しく展開されないケースがあります。",
    status: "CLOSED" as const,
    priority: "HIGH" as const,
    category: "バグ",
    ownerId: "user-1",
    contactId: "contact-3",
    companyId: "company-3",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-08T18:00:00Z",
    closedAt: "2026-03-07T16:00:00Z",
    createdAt: "2026-03-01T11:00:00Z",
    updatedAt: "2026-03-07T16:00:00Z",
  },
  {
    id: "ticket-7",
    subject: "権限設定の見直し依頼",
    description: "メンバー権限のユーザーがパイプライン設定を変更できてしまう問題があります。",
    status: "CLOSED" as const,
    priority: "URGENT" as const,
    category: "セキュリティ",
    ownerId: "user-3",
    contactId: "contact-4",
    companyId: "company-4",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-05T18:00:00Z",
    closedAt: "2026-03-04T14:00:00Z",
    createdAt: "2026-02-28T09:00:00Z",
    updatedAt: "2026-03-04T14:00:00Z",
  },
  {
    id: "ticket-8",
    subject: "モバイル画面のレイアウト崩れ",
    description: "スマートフォンでコンタクト詳細画面を開くと、レイアウトが崩れてボタンが押せない状態です。",
    status: "OPEN" as const,
    priority: "HIGH" as const,
    category: "バグ",
    ownerId: "user-4",
    contactId: "contact-10",
    companyId: "company-10",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-17T18:00:00Z",
    closedAt: null,
    createdAt: "2026-03-13T10:00:00Z",
    updatedAt: "2026-03-13T10:00:00Z",
  },
  {
    id: "ticket-9",
    subject: "データインポート機能の改善",
    description: "大量データ（10万件以上）のCSVインポート時にタイムアウトが発生します。バッチ処理の導入を検討してください。",
    status: "WAITING" as const,
    priority: "MEDIUM" as const,
    category: "機能改善",
    ownerId: "user-5",
    contactId: "contact-11",
    companyId: "company-11",
    pipelineId: null,
    stageId: null,
    slaDeadline: null,
    closedAt: null,
    createdAt: "2026-03-06T13:00:00Z",
    updatedAt: "2026-03-11T15:00:00Z",
  },
  {
    id: "ticket-10",
    subject: "請求書PDF生成エラー",
    description: "特定の取引で請求書PDFを生成するとエラーが発生します。金額が1000万円を超える場合に再現します。",
    status: "IN_PROGRESS" as const,
    priority: "HIGH" as const,
    category: "バグ",
    ownerId: "user-1",
    contactId: "contact-15",
    companyId: "company-4",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-16T18:00:00Z",
    closedAt: null,
    createdAt: "2026-03-09T09:30:00Z",
    updatedAt: "2026-03-13T16:00:00Z",
  },
  {
    id: "ticket-11",
    subject: "ワークフロー実行ログの追加要望",
    description: "ワークフローの実行履歴を詳細に確認できるログ機能が欲しいです。",
    status: "OPEN" as const,
    priority: "LOW" as const,
    category: "機能要望",
    ownerId: "user-2",
    contactId: "contact-9",
    companyId: "company-9",
    pipelineId: null,
    stageId: null,
    slaDeadline: null,
    closedAt: null,
    createdAt: "2026-03-07T11:00:00Z",
    updatedAt: "2026-03-07T11:00:00Z",
  },
  {
    id: "ticket-12",
    subject: "カスタムフィールドのバリデーション強化",
    description: "カスタムフィールドに数値型を設定しても、文字列が入力できてしまいます。入力バリデーションの強化をお願いします。",
    status: "CLOSED" as const,
    priority: "MEDIUM" as const,
    category: "バグ",
    ownerId: "user-3",
    contactId: "contact-14",
    companyId: "company-3",
    pipelineId: null,
    stageId: null,
    slaDeadline: "2026-03-10T18:00:00Z",
    closedAt: "2026-03-09T17:00:00Z",
    createdAt: "2026-03-04T14:00:00Z",
    updatedAt: "2026-03-09T17:00:00Z",
  },
];

// ===================== TASKS =====================
export const mockTasks: MockTask[] = [
  {
    id: "task-1",
    title: "テクノロジー社フォローアップ電話",
    description: "クラウド基盤構築の進捗確認と追加要件のヒアリング",
    dueDate: "2026-03-15T10:00:00Z",
    priority: "HIGH" as const,
    status: "IN_PROGRESS" as const,
    type: "CALL" as const,
    ownerId: "user-1",
    contactId: "contact-1",
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-03-13T14:00:00Z",
  },
  {
    id: "task-2",
    title: "サクラソフトウェア提案書作成",
    description: "MA導入の詳細提案書を作成する。ROI試算を含める。",
    dueDate: "2026-03-17T18:00:00Z",
    priority: "HIGH" as const,
    status: "NOT_STARTED" as const,
    type: "TODO" as const,
    ownerId: "user-2",
    contactId: "contact-2",
    createdAt: "2026-03-11T10:00:00Z",
    updatedAt: "2026-03-11T10:00:00Z",
  },
  {
    id: "task-3",
    title: "富士マーケティング見積送付",
    description: "デジタル広告運用の年間見積書を送付",
    dueDate: "2026-03-14T12:00:00Z",
    priority: "URGENT" as const,
    status: "COMPLETED" as const,
    type: "EMAIL" as const,
    ownerId: "user-1",
    contactId: "contact-3",
    createdAt: "2026-03-08T08:00:00Z",
    updatedAt: "2026-03-13T10:00:00Z",
  },
  {
    id: "task-4",
    title: "グローバルコンサルティングデモ準備",
    description: "DX推進ツールのデモ環境を構築し、カスタムシナリオを準備する",
    dueDate: "2026-03-18T10:00:00Z",
    priority: "HIGH" as const,
    status: "IN_PROGRESS" as const,
    type: "TODO" as const,
    ownerId: "user-3",
    contactId: "contact-4",
    createdAt: "2026-03-12T09:00:00Z",
    updatedAt: "2026-03-13T15:00:00Z",
  },
  {
    id: "task-5",
    title: "大和建設ヒアリングMTG",
    description: "施工管理システムの要件を詳しくヒアリングするためのミーティング",
    dueDate: "2026-03-16T14:00:00Z",
    priority: "MEDIUM" as const,
    status: "NOT_STARTED" as const,
    type: "MEETING" as const,
    ownerId: "user-4",
    contactId: "contact-5",
    createdAt: "2026-03-10T11:00:00Z",
    updatedAt: "2026-03-10T11:00:00Z",
  },
  {
    id: "task-6",
    title: "ネクストイノベーション契約条件確認",
    description: "AI予測分析ツールの契約条件を法務と確認",
    dueDate: "2026-03-15T17:00:00Z",
    priority: "MEDIUM" as const,
    status: "IN_PROGRESS" as const,
    type: "TODO" as const,
    ownerId: "user-2",
    contactId: "contact-6",
    createdAt: "2026-03-09T13:00:00Z",
    updatedAt: "2026-03-13T09:00:00Z",
  },
  {
    id: "task-7",
    title: "みずほFS月次レビュー報告",
    description: "金融システムモダナイゼーションの月次進捗レポートを作成",
    dueDate: "2026-03-20T18:00:00Z",
    priority: "HIGH" as const,
    status: "NOT_STARTED" as const,
    type: "TODO" as const,
    ownerId: "user-1",
    contactId: "contact-7",
    createdAt: "2026-03-12T08:00:00Z",
    updatedAt: "2026-03-12T08:00:00Z",
  },
  {
    id: "task-8",
    title: "北海道食品導入後フォローコール",
    description: "トレーサビリティシステムの導入後の使用感と改善点をヒアリング",
    dueDate: "2026-03-14T15:00:00Z",
    priority: "LOW" as const,
    status: "COMPLETED" as const,
    type: "CALL" as const,
    ownerId: "user-5",
    contactId: "contact-8",
    createdAt: "2026-03-07T10:00:00Z",
    updatedAt: "2026-03-14T15:30:00Z",
  },
  {
    id: "task-9",
    title: "エコエナジー技術仕様書確認",
    description: "ダッシュボード開発の技術仕様書を最終確認",
    dueDate: "2026-03-19T12:00:00Z",
    priority: "MEDIUM" as const,
    status: "NOT_STARTED" as const,
    type: "TODO" as const,
    ownerId: "user-3",
    contactId: "contact-9",
    createdAt: "2026-03-11T14:00:00Z",
    updatedAt: "2026-03-11T14:00:00Z",
  },
  {
    id: "task-10",
    title: "メディカルケアフォローメール送信",
    description: "電子カルテ連携デモ後のフォローアップメールを送信",
    dueDate: "2026-03-15T09:00:00Z",
    priority: "MEDIUM" as const,
    status: "COMPLETED" as const,
    type: "EMAIL" as const,
    ownerId: "user-4",
    contactId: "contact-10",
    createdAt: "2026-03-10T16:00:00Z",
    updatedAt: "2026-03-15T09:30:00Z",
  },
  {
    id: "task-11",
    title: "週次営業チームMTG",
    description: "今週のパイプラインレビューと来週のアクション確認",
    dueDate: "2026-03-14T16:00:00Z",
    priority: "MEDIUM" as const,
    status: "COMPLETED" as const,
    type: "MEETING" as const,
    ownerId: "user-1",
    contactId: null,
    createdAt: "2026-03-10T08:00:00Z",
    updatedAt: "2026-03-14T17:00:00Z",
  },
  {
    id: "task-12",
    title: "CRM月次レポート作成",
    description: "全体の営業実績とKPI達成状況のレポートを作成",
    dueDate: "2026-03-31T18:00:00Z",
    priority: "LOW" as const,
    status: "DEFERRED" as const,
    type: "TODO" as const,
    ownerId: "user-2",
    contactId: null,
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "task-13",
    title: "スマートロジスティクス初回商談",
    description: "物流最適化AIプラットフォームの初回提案に向けた商談準備",
    dueDate: "2026-03-21T10:00:00Z",
    priority: "HIGH" as const,
    status: "NOT_STARTED" as const,
    type: "MEETING" as const,
    ownerId: "user-5",
    contactId: "contact-11",
    createdAt: "2026-03-13T09:00:00Z",
    updatedAt: "2026-03-13T09:00:00Z",
  },
  {
    id: "task-14",
    title: "クリエイティブデザイン契約書確認",
    description: "ブランドリニューアルプロジェクトの契約書ドラフトを確認",
    dueDate: "2026-03-16T18:00:00Z",
    priority: "MEDIUM" as const,
    status: "NOT_STARTED" as const,
    type: "TODO" as const,
    ownerId: "user-2",
    contactId: "contact-12",
    createdAt: "2026-03-12T11:00:00Z",
    updatedAt: "2026-03-12T11:00:00Z",
  },
  {
    id: "task-15",
    title: "失注案件振り返りMTG",
    description: "ウェブサイトリプレイス案件の失注原因分析と改善策検討",
    dueDate: "2026-03-17T14:00:00Z",
    priority: "LOW" as const,
    status: "NOT_STARTED" as const,
    type: "MEETING" as const,
    ownerId: "user-3",
    contactId: "contact-12",
    createdAt: "2026-03-13T10:00:00Z",
    updatedAt: "2026-03-13T10:00:00Z",
  },
];

// ===================== ACTIVITIES =====================
export const mockActivities: MockActivity[] = [
  {
    id: "activity-1",
    type: "EMAIL" as const,
    subject: "クラウド基盤構築のご提案",
    body: "先日のお打ち合わせありがとうございました。ご提案資料を添付いたします。",
    metadata: null,
    userId: "user-1",
    contactId: "contact-1",
    companyId: "company-1",
    dealId: "deal-1",
    ticketId: null,
    createdAt: "2026-03-13T10:00:00Z",
  },
  {
    id: "activity-2",
    type: "CALL" as const,
    subject: "MA導入に関するヒアリングコール",
    body: "30分間のヒアリング。現在のマーケティング課題と期待効果を確認。",
    metadata: { duration: 30 },
    userId: "user-2",
    contactId: "contact-2",
    companyId: "company-2",
    dealId: "deal-2",
    ticketId: null,
    createdAt: "2026-03-12T14:00:00Z",
  },
  {
    id: "activity-3",
    type: "MEETING" as const,
    subject: "デジタル広告戦略ミーティング",
    body: "年間の広告運用戦略について1時間のミーティングを実施。",
    metadata: { duration: 60, location: "オンライン" },
    userId: "user-1",
    contactId: "contact-3",
    companyId: "company-3",
    dealId: "deal-3",
    ticketId: null,
    createdAt: "2026-03-11T15:00:00Z",
  },
  {
    id: "activity-4",
    type: "NOTE" as const,
    subject: "DXコンサル商談メモ",
    body: "先方は来期のIT予算として5000万円を見込んでいる。意思決定者は常務取締役。次回はデモを実施する予定。",
    metadata: null,
    userId: "user-3",
    contactId: "contact-4",
    companyId: "company-4",
    dealId: "deal-4",
    ticketId: null,
    createdAt: "2026-03-10T16:00:00Z",
  },
  {
    id: "activity-5",
    type: "DEAL_CREATED" as const,
    subject: "新規取引：施工管理システム導入",
    body: null,
    metadata: { dealAmount: 12000000 },
    userId: "user-4",
    contactId: "contact-5",
    companyId: "company-5",
    dealId: "deal-5",
    ticketId: null,
    createdAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "activity-6",
    type: "EMAIL" as const,
    subject: "AI予測分析ツール見積書送付",
    body: "見積書を送付いたします。ご確認のほどよろしくお願いいたします。",
    metadata: null,
    userId: "user-2",
    contactId: "contact-6",
    companyId: "company-6",
    dealId: "deal-6",
    ticketId: null,
    createdAt: "2026-03-08T11:00:00Z",
  },
  {
    id: "activity-7",
    type: "DEAL_STAGE_CHANGED" as const,
    subject: "金融システムモダナイゼーション：初回商談→提案中",
    body: null,
    metadata: { fromStage: "初回商談", toStage: "提案中" },
    userId: "user-1",
    contactId: "contact-7",
    companyId: "company-7",
    dealId: "deal-7",
    ticketId: null,
    createdAt: "2026-03-05T09:00:00Z",
  },
  {
    id: "activity-8",
    type: "TICKET_CREATED" as const,
    subject: "チケット作成：ログイン認証エラーが頻発",
    body: null,
    metadata: { ticketPriority: "HIGH" },
    userId: "user-3",
    contactId: "contact-1",
    companyId: "company-1",
    dealId: null,
    ticketId: "ticket-1",
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "activity-9",
    type: "CALL" as const,
    subject: "食品トレーサビリティ導入後サポートコール",
    body: "システム稼働後の運用状況を確認。おおむね問題なし。一部UIの改善要望あり。",
    metadata: { duration: 20 },
    userId: "user-5",
    contactId: "contact-8",
    companyId: "company-8",
    dealId: "deal-8",
    ticketId: null,
    createdAt: "2026-03-07T15:00:00Z",
  },
  {
    id: "activity-10",
    type: "MEETING" as const,
    subject: "再エネダッシュボード要件定義MTG",
    body: "ダッシュボードの表示項目とKPI定義について2時間のワークショップを実施。",
    metadata: { duration: 120, location: "エコエナジー本社" },
    userId: "user-3",
    contactId: "contact-9",
    companyId: "company-9",
    dealId: "deal-9",
    ticketId: null,
    createdAt: "2026-03-06T13:00:00Z",
  },
  {
    id: "activity-11",
    type: "FORM_SUBMISSION" as const,
    subject: "資料ダウンロードフォーム送信",
    body: null,
    metadata: { formName: "製品資料ダウンロード", formId: "form-1" },
    userId: null,
    contactId: "contact-10",
    companyId: "company-10",
    dealId: null,
    ticketId: null,
    createdAt: "2026-03-04T10:00:00Z",
  },
  {
    id: "activity-12",
    type: "LIFECYCLE_CHANGE" as const,
    subject: "ライフサイクル変更：LEAD→MQL",
    body: null,
    metadata: { from: "LEAD", to: "MQL" },
    userId: null,
    contactId: "contact-16",
    companyId: "company-6",
    dealId: null,
    ticketId: null,
    createdAt: "2026-03-03T08:00:00Z",
  },
  {
    id: "activity-13",
    type: "EMAIL" as const,
    subject: "セキュリティ監査サービスのご案内",
    body: "みずほFS様向けにセキュリティ監査サービスの概要をご案内いたします。",
    metadata: null,
    userId: "user-1",
    contactId: "contact-7",
    companyId: "company-7",
    dealId: "deal-15",
    ticketId: null,
    createdAt: "2026-03-02T11:00:00Z",
  },
  {
    id: "activity-14",
    type: "PAGE_VIEW" as const,
    subject: "料金ページ閲覧",
    body: null,
    metadata: { page: "/pricing", duration: 180 },
    userId: null,
    contactId: "contact-11",
    companyId: "company-11",
    dealId: null,
    ticketId: null,
    createdAt: "2026-03-01T20:00:00Z",
  },
  {
    id: "activity-15",
    type: "NOTE" as const,
    subject: "CRM統合プロジェクト完了メモ",
    body: "全フェーズ完了。顧客満足度も高い。追加案件の打診あり。",
    metadata: null,
    userId: "user-1",
    contactId: "contact-15",
    companyId: "company-4",
    dealId: "deal-13",
    ticketId: null,
    createdAt: "2026-03-10T17:00:00Z",
  },
  {
    id: "activity-16",
    type: "TASK" as const,
    subject: "タスク完了：富士マーケティング見積送付",
    body: null,
    metadata: { taskId: "task-3" },
    userId: "user-1",
    contactId: "contact-3",
    companyId: "company-3",
    dealId: "deal-3",
    ticketId: null,
    createdAt: "2026-03-13T10:00:00Z",
  },
  {
    id: "activity-17",
    type: "CALL" as const,
    subject: "電子カルテ連携デモ日程調整コール",
    body: "来週月曜にオンラインデモを実施することで合意。",
    metadata: { duration: 15 },
    userId: "user-4",
    contactId: "contact-10",
    companyId: "company-10",
    dealId: "deal-10",
    ticketId: null,
    createdAt: "2026-02-28T14:00:00Z",
  },
  {
    id: "activity-18",
    type: "MEETING" as const,
    subject: "ブランドリニューアルキックオフMTG",
    body: "プロジェクトの目標、スケジュール、体制について合意。",
    metadata: { duration: 90, location: "オンライン" },
    userId: "user-2",
    contactId: "contact-12",
    companyId: "company-12",
    dealId: "deal-12",
    ticketId: null,
    createdAt: "2026-02-25T10:00:00Z",
  },
  {
    id: "activity-19",
    type: "DEAL_STAGE_CHANGED" as const,
    subject: "食品トレーサビリティ：交渉中→契約締結",
    body: null,
    metadata: { fromStage: "交渉中", toStage: "契約締結" },
    userId: "user-5",
    contactId: "contact-8",
    companyId: "company-8",
    dealId: "deal-8",
    ticketId: null,
    createdAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "activity-20",
    type: "EMAIL" as const,
    subject: "物流AIプラットフォーム資料送付",
    body: "スマートロジスティクス様向けに製品概要資料を送付いたしました。",
    metadata: null,
    userId: "user-5",
    contactId: "contact-11",
    companyId: "company-11",
    dealId: "deal-11",
    ticketId: null,
    createdAt: "2026-02-20T09:00:00Z",
  },
];

// ===================== NOTES =====================
export const mockNotes: MockNote[] = [
  {
    id: "note-1",
    body: "テクノロジー社の山本CTO は技術的な意思決定権を持っている。提案時は具体的な技術仕様とパフォーマンスデータを重視する傾向あり。",
    userId: "user-1",
    contactId: "contact-1",
    companyId: "company-1",
    dealId: "deal-1",
    ticketId: null,
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "note-2",
    body: "サクラソフトウェアはMA導入に意欲的。競合はSalesforce Marketing Cloud。価格と日本語サポートで差別化を図る。",
    userId: "user-2",
    contactId: "contact-2",
    companyId: "company-2",
    dealId: "deal-2",
    ticketId: null,
    createdAt: "2026-03-08T14:00:00Z",
    updatedAt: "2026-03-08T14:00:00Z",
  },
  {
    id: "note-3",
    body: "富士マーケティングの田中社長は業界歴25年。信頼関係構築が最重要。短期的な結果よりも長期パートナーシップを重視。",
    userId: "user-1",
    contactId: "contact-3",
    companyId: "company-3",
    dealId: "deal-3",
    ticketId: null,
    createdAt: "2026-03-05T16:00:00Z",
    updatedAt: "2026-03-05T16:00:00Z",
  },
  {
    id: "note-4",
    body: "グローバルコンサルティングはDX推進の大型案件。予算は5000万円規模。決裁プロセスが複雑で、常務取締役の承認が必要。",
    userId: "user-3",
    contactId: "contact-4",
    companyId: "company-4",
    dealId: "deal-4",
    ticketId: null,
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-10T16:00:00Z",
  },
  {
    id: "note-5",
    body: "みずほFSとの金融システム案件は、セキュリティ要件が厳しい。FISC安全対策基準への準拠が必須条件。",
    userId: "user-1",
    contactId: "contact-7",
    companyId: "company-7",
    dealId: "deal-7",
    ticketId: null,
    createdAt: "2026-02-15T11:00:00Z",
    updatedAt: "2026-03-12T09:00:00Z",
  },
  {
    id: "note-6",
    body: "北海道食品のトレーサビリティシステムは無事稼働開始。追加の分析ダッシュボード開発の相談あり。",
    userId: "user-5",
    contactId: "contact-8",
    companyId: "company-8",
    dealId: "deal-8",
    ticketId: null,
    createdAt: "2026-02-20T15:00:00Z",
    updatedAt: "2026-02-20T15:00:00Z",
  },
  {
    id: "note-7",
    body: "エコエナジーのダッシュボードプロジェクトは順調。リアルタイムデータ連携のPoCが成功。次のフェーズに進む予定。",
    userId: "user-3",
    contactId: "contact-9",
    companyId: "company-9",
    dealId: "deal-9",
    ticketId: null,
    createdAt: "2026-03-06T14:00:00Z",
    updatedAt: "2026-03-06T14:00:00Z",
  },
  {
    id: "note-8",
    body: "全社CRM統合プロジェクト完了。顧客からの評価も高く、事例紹介の許可をいただいた。マーケティングチームに共有済み。",
    userId: "user-1",
    contactId: "contact-15",
    companyId: "company-4",
    dealId: "deal-13",
    ticketId: null,
    createdAt: "2026-03-10T17:00:00Z",
    updatedAt: "2026-03-10T17:00:00Z",
  },
  {
    id: "note-9",
    body: "ウェブサイトリプレイス案件は失注。理由は予算不足。来期に再度検討の可能性あり。6ヶ月後にフォローアップ予定。",
    userId: "user-3",
    contactId: "contact-12",
    companyId: "company-12",
    dealId: "deal-14",
    ticketId: null,
    createdAt: "2026-02-28T16:00:00Z",
    updatedAt: "2026-02-28T16:00:00Z",
  },
  {
    id: "note-10",
    body: "ログイン認証エラーの原因を特定。トークンの有効期限設定に問題があった。修正パッチを適用中。",
    userId: "user-3",
    contactId: "contact-1",
    companyId: "company-1",
    dealId: null,
    ticketId: "ticket-1",
    createdAt: "2026-03-13T14:00:00Z",
    updatedAt: "2026-03-13T14:00:00Z",
  },
];

// ===================== EMAIL TEMPLATES =====================
export const mockEmailTemplates = [
  {
    id: "template-1",
    name: "初回アプローチメール",
    subject: "{{company_name}}様 - サービスのご案内",
    body: "{{contact_name}}様\n\nお世話になっております。{{sender_name}}と申します。\n\n貴社の{{industry}}分野でのさらなる成長をご支援できればと思い、ご連絡いたしました。\n\n弊社では、{{product_name}}を通じて、業務効率化と売上向上をサポートしております。\n\nぜひ一度、30分ほどお時間をいただけますと幸いです。\n\nよろしくお願いいたします。",
    category: "営業",
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "template-2",
    name: "フォローアップメール",
    subject: "Re: 先日のお打ち合わせについて",
    body: "{{contact_name}}様\n\n先日は貴重なお時間をいただき、ありがとうございました。\n\nお打ち合わせでご質問いただいた件について、添付の資料にまとめましたのでご確認ください。\n\n追加のご質問やご要望がございましたら、お気軽にお申し付けください。\n\n引き続きよろしくお願いいたします。",
    category: "フォローアップ",
    createdAt: "2025-10-15T00:00:00Z",
    updatedAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "template-3",
    name: "見積送付メール",
    subject: "【見積書】{{deal_name}} - {{company_name}}様",
    body: "{{contact_name}}様\n\nお世話になっております。\n\n{{deal_name}}の見積書を添付にてお送りいたします。\n\n【お見積金額】{{deal_amount}}\n【有効期限】発行日より30日間\n\nご不明な点がございましたら、お気軽にご連絡ください。\n\nよろしくお願いいたします。",
    category: "見積",
    createdAt: "2025-11-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "template-4",
    name: "ウェルカムメール",
    subject: "{{company_name}}へようこそ - ご利用開始のご案内",
    body: "{{contact_name}}様\n\nこのたびは弊社サービスをご契約いただき、誠にありがとうございます。\n\n以下の手順でご利用を開始いただけます。\n\n1. ログインURL: {{login_url}}\n2. 初期設定ガイド: {{guide_url}}\n3. サポート窓口: support@example.com\n\nオンボーディングセッションをご希望の場合は、お気軽にお申し付けください。\n\n今後ともよろしくお願いいたします。",
    category: "オンボーディング",
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "template-5",
    name: "契約更新のご案内",
    subject: "【重要】{{deal_name}} 契約更新のご案内",
    body: "{{contact_name}}様\n\nお世話になっております。\n\n{{deal_name}}のご契約が{{expiry_date}}に満了を迎えます。\n\n引き続きのご利用をご検討いただけますと幸いです。更新に際しましてのご質問やご相談がございましたら、担当の{{owner_name}}までお気軽にご連絡ください。\n\n今後ともよろしくお願いいたします。",
    category: "契約管理",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
];

// ===================== EMAIL CAMPAIGNS =====================
export const mockEmailCampaigns = [
  {
    id: "campaign-1",
    name: "春の新規顧客獲得キャンペーン",
    status: "SENT" as const,
    templateId: "template-1",
    scheduledAt: "2026-03-01T09:00:00Z",
    sentAt: "2026-03-01T09:00:00Z",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-03-01T09:00:00Z",
    stats: { id: "stats-1", campaignId: "campaign-1", sent: 1500, delivered: 1450, opened: 580, clicked: 145, bounced: 50, unsubscribed: 12 },
  },
  {
    id: "campaign-2",
    name: "製品アップデート告知",
    status: "SENT" as const,
    templateId: "template-2",
    scheduledAt: "2026-02-20T10:00:00Z",
    sentAt: "2026-02-20T10:00:00Z",
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-02-20T10:00:00Z",
    stats: { id: "stats-2", campaignId: "campaign-2", sent: 3200, delivered: 3150, opened: 1260, clicked: 420, bounced: 50, unsubscribed: 8 },
  },
  {
    id: "campaign-3",
    name: "ウェビナー招待メール",
    status: "SCHEDULED" as const,
    templateId: "template-1",
    scheduledAt: "2026-03-20T09:00:00Z",
    sentAt: null,
    createdAt: "2026-03-10T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
    stats: null,
  },
  {
    id: "campaign-4",
    name: "事例紹介ニュースレター",
    status: "SENT" as const,
    templateId: "template-2",
    scheduledAt: "2026-02-01T09:00:00Z",
    sentAt: "2026-02-01T09:00:00Z",
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-02-01T09:00:00Z",
    stats: { id: "stats-4", campaignId: "campaign-4", sent: 2800, delivered: 2750, opened: 990, clicked: 275, bounced: 50, unsubscribed: 5 },
  },
  {
    id: "campaign-5",
    name: "年度末特別プロモーション",
    status: "SENDING" as const,
    templateId: "template-3",
    scheduledAt: "2026-03-14T09:00:00Z",
    sentAt: "2026-03-14T09:00:00Z",
    createdAt: "2026-03-05T00:00:00Z",
    updatedAt: "2026-03-14T09:30:00Z",
    stats: { id: "stats-5", campaignId: "campaign-5", sent: 800, delivered: 790, opened: 200, clicked: 45, bounced: 10, unsubscribed: 2 },
  },
  {
    id: "campaign-6",
    name: "顧客満足度アンケート",
    status: "SENT" as const,
    templateId: "template-4",
    scheduledAt: "2026-01-15T10:00:00Z",
    sentAt: "2026-01-15T10:00:00Z",
    createdAt: "2026-01-05T00:00:00Z",
    updatedAt: "2026-01-15T10:00:00Z",
    stats: { id: "stats-6", campaignId: "campaign-6", sent: 500, delivered: 495, opened: 248, clicked: 150, bounced: 5, unsubscribed: 1 },
  },
  {
    id: "campaign-7",
    name: "新機能リリース告知",
    status: "DRAFT" as const,
    templateId: null,
    scheduledAt: null,
    sentAt: null,
    createdAt: "2026-03-12T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
    stats: null,
  },
  {
    id: "campaign-8",
    name: "休眠顧客復活キャンペーン",
    status: "CANCELLED" as const,
    templateId: "template-5",
    scheduledAt: "2026-03-10T09:00:00Z",
    sentAt: null,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-09T00:00:00Z",
    stats: null,
  },
];

// ===================== FORMS =====================
export const mockForms = [
  {
    id: "form-1",
    name: "製品資料ダウンロード",
    fields: [
      { name: "lastName", label: "姓", type: "text", required: true },
      { name: "firstName", label: "名", type: "text", required: true },
      { name: "email", label: "メールアドレス", type: "email", required: true },
      { name: "company", label: "会社名", type: "text", required: true },
      { name: "phone", label: "電話番号", type: "tel", required: false },
    ],
    settings: { redirectUrl: "/thank-you", notifyEmail: "sales@example.com" },
    submissions: 342,
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "form-2",
    name: "お問い合わせフォーム",
    fields: [
      { name: "lastName", label: "姓", type: "text", required: true },
      { name: "firstName", label: "名", type: "text", required: true },
      { name: "email", label: "メールアドレス", type: "email", required: true },
      { name: "company", label: "会社名", type: "text", required: false },
      { name: "category", label: "お問い合わせ種別", type: "select", required: true, options: ["製品について", "料金について", "サポート", "パートナーシップ", "その他"] },
      { name: "message", label: "お問い合わせ内容", type: "textarea", required: true },
    ],
    settings: { redirectUrl: "/contact-thank-you", notifyEmail: "info@example.com" },
    submissions: 189,
    createdAt: "2025-07-01T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "form-3",
    name: "ウェビナー参加申込",
    fields: [
      { name: "lastName", label: "姓", type: "text", required: true },
      { name: "firstName", label: "名", type: "text", required: true },
      { name: "email", label: "メールアドレス", type: "email", required: true },
      { name: "company", label: "会社名", type: "text", required: true },
      { name: "jobTitle", label: "役職", type: "text", required: false },
      { name: "interest", label: "関心のあるトピック", type: "checkbox", options: ["CRM活用", "MA導入", "データ分析", "AI活用"] },
    ],
    settings: { redirectUrl: "/webinar-registered", notifyEmail: "marketing@example.com" },
    submissions: 567,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
  },
  {
    id: "form-4",
    name: "無料トライアル申込",
    fields: [
      { name: "lastName", label: "姓", type: "text", required: true },
      { name: "firstName", label: "名", type: "text", required: true },
      { name: "email", label: "ビジネスメール", type: "email", required: true },
      { name: "company", label: "会社名", type: "text", required: true },
      { name: "employeeCount", label: "従業員数", type: "select", required: true, options: ["1-10名", "11-50名", "51-200名", "201-1000名", "1001名以上"] },
      { name: "phone", label: "電話番号", type: "tel", required: true },
    ],
    settings: { redirectUrl: "/trial-start", notifyEmail: "sales@example.com" },
    submissions: 234,
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "form-5",
    name: "パートナー申請",
    fields: [
      { name: "companyName", label: "会社名", type: "text", required: true },
      { name: "contactName", label: "担当者名", type: "text", required: true },
      { name: "email", label: "メールアドレス", type: "email", required: true },
      { name: "phone", label: "電話番号", type: "tel", required: true },
      { name: "partnerType", label: "パートナータイプ", type: "select", required: true, options: ["リセラー", "テクノロジー", "コンサルティング", "エージェンシー"] },
      { name: "message", label: "申請理由", type: "textarea", required: true },
    ],
    settings: { redirectUrl: "/partner-thank-you", notifyEmail: "partners@example.com" },
    submissions: 45,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "form-6",
    name: "顧客満足度アンケート",
    fields: [
      { name: "satisfaction", label: "総合満足度", type: "rating", required: true },
      { name: "nps", label: "推薦度(0-10)", type: "number", required: true },
      { name: "feedback", label: "ご意見・ご要望", type: "textarea", required: false },
      { name: "canContact", label: "追加ヒアリングへの協力", type: "checkbox", options: ["協力可能"] },
    ],
    settings: { redirectUrl: "/survey-thank-you", notifyEmail: "cs@example.com" },
    submissions: 156,
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
];

// ===================== LANDING PAGES =====================
export const mockLandingPages = [
  {
    id: "lp-1",
    title: "CRMプラットフォーム - 無料トライアル",
    slug: "crm-free-trial",
    content: { hero: "業務効率を劇的に改善するCRM", cta: "14日間無料でお試し" },
    published: true,
    views: 12500,
    conversions: 450,
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "lp-2",
    title: "マーケティングオートメーション導入ガイド",
    slug: "ma-guide",
    content: { hero: "MA導入で売上2倍を実現", cta: "無料ガイドをダウンロード" },
    published: true,
    views: 8300,
    conversions: 620,
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "lp-3",
    title: "2026年春ウェビナー - AI活用最前線",
    slug: "spring-webinar-2026",
    content: { hero: "AIが変える営業のミライ", cta: "今すぐ参加登録" },
    published: true,
    views: 3200,
    conversions: 280,
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
  },
  {
    id: "lp-4",
    title: "導入事例集 - 業界別成功ストーリー",
    slug: "case-studies",
    content: { hero: "150社以上の導入実績", cta: "事例集をダウンロード" },
    published: true,
    views: 5600,
    conversions: 340,
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "lp-5",
    title: "パートナープログラムのご案内",
    slug: "partner-program",
    content: { hero: "一緒にビジネスを成長させませんか", cta: "パートナー申請はこちら" },
    published: false,
    views: 0,
    conversions: 0,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
];

// ===================== KNOWLEDGE BASE ARTICLES =====================
export const mockKnowledgeBaseArticles = [
  {
    id: "kb-1",
    title: "初期設定ガイド - はじめてのCRM",
    body: "CRMプラットフォームの初期設定手順を説明します。アカウント作成後、まずチーム設定、パイプライン設定、インテグレーション設定の3ステップを完了してください。",
    category: "はじめに",
    published: true,
    views: 2340,
    helpful: 189,
    notHelpful: 12,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "kb-2",
    title: "コンタクト管理の基本",
    body: "コンタクトの追加、編集、削除の方法と、ライフサイクルステージの管理方法について説明します。CSVインポート機能を使って、既存のコンタクトデータを一括登録することも可能です。",
    category: "CRM",
    published: true,
    views: 1850,
    helpful: 156,
    notHelpful: 8,
    createdAt: "2025-06-15T00:00:00Z",
    updatedAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "kb-3",
    title: "パイプラインとステージの設定",
    body: "取引パイプラインの作成方法とステージのカスタマイズ方法を説明します。複数のパイプラインを作成して、異なる商材や営業プロセスに対応できます。",
    category: "CRM",
    published: true,
    views: 1200,
    helpful: 98,
    notHelpful: 5,
    createdAt: "2025-07-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "kb-4",
    title: "メールテンプレートの作成と活用",
    body: "再利用可能なメールテンプレートの作成方法と、変数の使い方を説明します。テンプレートを使うことで、パーソナライズされたメールを効率的に送信できます。",
    category: "マーケティング",
    published: true,
    views: 980,
    helpful: 82,
    notHelpful: 3,
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "kb-5",
    title: "ワークフロー自動化ガイド",
    body: "ワークフローを使った業務自動化の設定方法を説明します。トリガー、条件、アクションの組み合わせで、営業プロセスを自動化できます。",
    category: "自動化",
    published: true,
    views: 1560,
    helpful: 134,
    notHelpful: 11,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "kb-6",
    title: "レポートとダッシュボードの活用",
    body: "カスタムレポートの作成方法と、ダッシュボードのウィジェット設定について説明します。KPIの可視化と営業活動の分析に活用してください。",
    category: "レポート",
    published: true,
    views: 870,
    helpful: 67,
    notHelpful: 4,
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-02-20T00:00:00Z",
  },
  {
    id: "kb-7",
    title: "API連携ガイド",
    body: "REST APIを使った外部システムとの連携方法を説明します。認証方法、エンドポイント一覧、リクエスト/レスポンスの例を紹介します。",
    category: "開発者向け",
    published: true,
    views: 650,
    helpful: 52,
    notHelpful: 7,
    createdAt: "2025-11-01T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "kb-8",
    title: "セキュリティとアクセス権限の設定",
    body: "ユーザーロール（管理者、マネージャー、メンバー）の権限設定と、データアクセス制御について説明します。チームの規模に応じた適切な権限設定を推奨します。",
    category: "管理",
    published: false,
    views: 0,
    helpful: 0,
    notHelpful: 0,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
];

// ===================== WORKFLOWS =====================
export const mockWorkflows: MockWorkflow[] = [
  {
    id: "wf-1",
    name: "新規リード自動フォローアップ",
    type: "contact",
    active: true,
    lastModified: "2026-03-12T10:30:00Z",
    enrolledCount: 342,
    trigger: "フォーム送信時",
    actions: ["ウェルカムメール送信", "3日後フォローアップメール", "担当者に通知", "タスク作成"],
    createdAt: "2025-10-01T00:00:00Z",
  },
  {
    id: "wf-2",
    name: "取引ステージ変更通知",
    type: "deal",
    active: true,
    lastModified: "2026-03-10T14:00:00Z",
    enrolledCount: 156,
    trigger: "取引ステージ変更時",
    actions: ["マネージャーに通知", "Slack通知", "アクティビティ記録"],
    createdAt: "2025-11-15T00:00:00Z",
  },
  {
    id: "wf-3",
    name: "チケットSLAエスカレーション",
    type: "ticket",
    active: true,
    lastModified: "2026-03-08T09:00:00Z",
    enrolledCount: 89,
    trigger: "SLA期限超過時",
    actions: ["優先度を上げる", "マネージャーに通知", "担当者再アサイン"],
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "wf-4",
    name: "顧客満足度調査自動送信",
    type: "contact",
    active: true,
    lastModified: "2026-03-05T16:00:00Z",
    enrolledCount: 1245,
    trigger: "チケット解決後3日",
    actions: ["CSATアンケート送信", "スコア記録", "低スコア時にアラート"],
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "wf-5",
    name: "新規会社登録時の自動処理",
    type: "company",
    active: false,
    lastModified: "2026-02-28T11:00:00Z",
    enrolledCount: 0,
    trigger: "新規会社作成時",
    actions: ["業界分類の自動設定", "担当者アサイン", "ウェルカムメール送信"],
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "wf-6",
    name: "失注フォローアップ",
    type: "deal",
    active: true,
    lastModified: "2026-03-01T08:00:00Z",
    enrolledCount: 67,
    trigger: "取引が失注に変更時",
    actions: ["失注理由ヒアリングメール", "30日後再アプローチメール", "担当者タスク作成"],
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "wf-7",
    name: "MQLからSQLへの自動昇格",
    type: "contact",
    active: true,
    lastModified: "2026-03-11T13:00:00Z",
    enrolledCount: 523,
    trigger: "リードスコア50点以上",
    actions: ["ライフサイクル変更", "営業チームに通知", "ミーティングリンク送信"],
    createdAt: "2025-08-15T00:00:00Z",
  },
  {
    id: "wf-8",
    name: "契約更新リマインダー",
    type: "deal",
    active: false,
    lastModified: "2026-02-20T10:00:00Z",
    enrolledCount: 0,
    trigger: "契約終了90日前",
    actions: ["担当者に通知", "更新提案メール", "タスク作成", "マネージャーCC"],
    createdAt: "2025-11-01T00:00:00Z",
  },
];

// ===================== SEQUENCES =====================
export const mockSequences: MockSequence[] = [
  {
    id: "seq-1",
    name: "新規リードアプローチ",
    steps: [
      { type: "email", label: "自己紹介メール", delay: 0 },
      { type: "wait", label: "3日待機", delay: 3 },
      { type: "email", label: "事例紹介メール", delay: 0 },
      { type: "wait", label: "2日待機", delay: 2 },
      { type: "task", label: "電話フォロー", delay: 0 },
      { type: "email", label: "最終フォローアップ", delay: 0 },
    ],
    stepsCount: 6,
    enrolled: 234,
    replyRate: 18.5,
    meetingRate: 8.2,
    active: true,
    createdAt: "2026-01-15T00:00:00Z",
    ownerId: "user-1",
    ownerName: "佐藤 匠",
  },
  {
    id: "seq-2",
    name: "展示会リードフォロー",
    steps: [
      { type: "email", label: "お礼メール", delay: 0 },
      { type: "wait", label: "1日待機", delay: 1 },
      { type: "email", label: "資料送付", delay: 0 },
      { type: "wait", label: "3日待機", delay: 3 },
      { type: "call", label: "フォローコール", delay: 0 },
      { type: "email", label: "ミーティング提案", delay: 0 },
    ],
    stepsCount: 6,
    enrolled: 156,
    replyRate: 24.3,
    meetingRate: 12.1,
    active: true,
    createdAt: "2026-02-01T00:00:00Z",
    ownerId: "user-1",
    ownerName: "佐藤 匠",
  },
  {
    id: "seq-3",
    name: "休眠顧客復活",
    steps: [
      { type: "email", label: "近況伺い", delay: 0 },
      { type: "wait", label: "5日待機", delay: 5 },
      { type: "email", label: "新機能案内", delay: 0 },
      { type: "wait", label: "3日待機", delay: 3 },
      { type: "task", label: "個別フォロー検討", delay: 0 },
    ],
    stepsCount: 5,
    enrolled: 89,
    replyRate: 12.4,
    meetingRate: 4.5,
    active: true,
    createdAt: "2026-02-10T00:00:00Z",
    ownerId: "user-2",
    ownerName: "田中 美咲",
  },
  {
    id: "seq-4",
    name: "デモ後フォローアップ",
    steps: [
      { type: "email", label: "デモお礼＋資料", delay: 0 },
      { type: "wait", label: "2日待機", delay: 2 },
      { type: "email", label: "Q&Aフォロー", delay: 0 },
      { type: "wait", label: "3日待機", delay: 3 },
      { type: "call", label: "意思決定確認コール", delay: 0 },
      { type: "email", label: "見積提案", delay: 0 },
      { type: "wait", label: "5日待機", delay: 5 },
      { type: "email", label: "最終確認", delay: 0 },
    ],
    stepsCount: 8,
    enrolled: 78,
    replyRate: 32.1,
    meetingRate: 18.6,
    active: true,
    createdAt: "2026-01-20T00:00:00Z",
    ownerId: "user-1",
    ownerName: "佐藤 匠",
  },
  {
    id: "seq-5",
    name: "ウェビナー参加者フォロー",
    steps: [
      { type: "email", label: "録画・資料共有", delay: 0 },
      { type: "wait", label: "2日待機", delay: 2 },
      { type: "email", label: "関連コンテンツ", delay: 0 },
      { type: "task", label: "スコア確認・アプローチ判断", delay: 0 },
    ],
    stepsCount: 4,
    enrolled: 312,
    replyRate: 15.8,
    meetingRate: 6.3,
    active: false,
    createdAt: "2026-02-15T00:00:00Z",
    ownerId: "user-2",
    ownerName: "田中 美咲",
  },
  {
    id: "seq-6",
    name: "アップセル提案",
    steps: [
      { type: "email", label: "利用状況レビュー", delay: 0 },
      { type: "wait", label: "3日待機", delay: 3 },
      { type: "email", label: "上位プラン紹介", delay: 0 },
      { type: "wait", label: "4日待機", delay: 4 },
      { type: "call", label: "個別ヒアリング", delay: 0 },
      { type: "email", label: "カスタム提案書", delay: 0 },
    ],
    stepsCount: 6,
    enrolled: 45,
    replyRate: 22.2,
    meetingRate: 15.6,
    active: true,
    createdAt: "2026-03-01T00:00:00Z",
    ownerId: "user-1",
    ownerName: "佐藤 匠",
  },
];

// ===================== HELPER FUNCTIONS =====================

/** Look up a user by ID, returning select fields */
export function getUserById(id: string) {
  return mockUsers.find((u) => u.id === id) || null;
}

/** Look up a user and return {id, name} */
export function getUserSelect(id: string | null | undefined) {
  if (!id) return null;
  const u = getUserById(id);
  return u ? { id: u.id, name: u.name } : null;
}

/** Look up a company by ID */
export function getCompanyById(id: string) {
  return mockCompanies.find((c) => c.id === id) || null;
}

/** Look up a company and return {id, name} */
export function getCompanySelect(id: string | null | undefined) {
  if (!id) return null;
  const c = getCompanyById(id);
  return c ? { id: c.id, name: c.name } : null;
}

/** Look up a contact by ID */
export function getContactById(id: string) {
  return mockContacts.find((c) => c.id === id) || null;
}

/** Look up a contact and return {id, firstName, lastName} */
export function getContactSelect(id: string | null | undefined) {
  if (!id) return null;
  const c = getContactById(id);
  return c ? { id: c.id, firstName: c.firstName, lastName: c.lastName } : null;
}

/** Look up a stage by ID */
export function getStageById(id: string) {
  return mockPipelineStages.find((s) => s.id === id) || null;
}

/** Look up a pipeline by ID */
export function getPipelineById(id: string) {
  return mockPipelines.find((p) => p.id === id) || null;
}

/** Case-insensitive substring match */
export function includesCI(text: string | null | undefined, search: string): boolean {
  if (!text) return false;
  return text.toLowerCase().includes(search.toLowerCase());
}
